### ISSUE TITLE
Document how to override styled-jsx styles from our library components

### ISSUE THREAD

**Issue by ismay** [dhis2/notes#108]
It's fairly involved, so it'd be good to document a recommended approach, and what caveats there are (it might break, not recommended, etc.). See here: https://dhis2.slack.com/archives/CBM8LNEQM/p1589966296020200?thread_ts=1589961187.000500&cid=CBM8LNEQM

**Comment by Mohammer5** [comment]
Let's put it directly here:

> So regarding styled-jsx and our “mechanism to allow style overrides”. It’s pretty dreadful…. The basic idea is good: each ui-core component should be able to accept a custom className and we style via that. But then we encounter all these specificity issues:
> 1) The selectors produced by styled-jsx have a higher specificity than you’d normally use when writing normal CSS. Usually these end up being <tagName>.classname or .<className>.<className>, while in the app stylesheet you’d probably write .<className> selectors.
> 2) But I believe that even writing selectors with an equal specificity won’t do the trick, because the styled-jsx style declarations end up being further down in the DOM than the styles in which you are trying to do the style-override.
> I’m not fully sure if the second point is a problem only when working in the library, with styled-jsx, or if you would encounter it when writing apps too. But it’s this point that bothers me the most…
The only way to avoid using !important is to write selectors with a higher specificity. In this case that would be quite an involved process:
> - You would probably need to add a custom className to the Transfer in your app
> - And use that in your selector
> ```css
> .custom-transfer-classname div.select {
>     margin: 0;
>     border: 1px solid red;
> }
> ```
> (by @HendrikThePendric)

> It'd be ugly, but you should be able to do
> ```css
> .select.select.select {
>   /* ... */
> }
> ```
> (by @Mohammer5)

**Comment by varl** [comment]
_(Without being aware of the specifics that lead to this discussion popping up again)_

To override internal CSS is a shortcut that leads to harder-to-maintain code because of the coupling it introduces. The argument is similar to code reuse via composition vs. inheritance.

The `className` prop was initially omitted as it is not meant for wide-spread use; we considered it an anti-pattern for the UI components. It was added for cautious _internal_ use to enable us to use `styled-jsx/resolve` in situations where the alternative was too heavy.

Using the `className` prop from an App is a big red flag and we should not endorse that style. It breaks many of the benefits we want to extract from our component library, one of which is to be able to rely on semver to automatically update the UI components across all our apps.

If we rely on `className` overrides, then a patch-version bump may break components in an App, which is exactly the situation we do not want.

**Comment by ismay** [comment]
> _(Without being aware of the specifics that lead to this discussion popping up again)_
> 
> To override internal CSS is a shortcut that leads to harder-to-maintain code because of the coupling it introduces. The argument is similar to code reuse via composition vs. inheritance.
> 
> The `className` prop was initially omitted as it is not meant for wide-spread use; we considered it an anti-pattern for the UI components. It was added for cautious _internal_ use to enable us to use `styled-jsx/resolve` in situations where the alternative was too heavy.
> 
> Using the `className` prop from an App is a big red flag and we should not endorse that style. It breaks many of the benefits we want to extract from our component library, one of which is to be able to rely on semver to automatically update the UI components across all our apps.
> 
> If we rely on `className` overrides, then a patch-version bump may break components in an App, which is exactly the situation we do not want.

I think we're all on the same page here. The reason this cropped up is that we ended up explaining this to people again and again, so we thought it'd be a good idea to put it somewhere.

To see how I worded it see here: https://github.com/dhis2/notes/pull/110/files#diff-f6fd534f8bedfe9a4bea5d367949f9faR1-R35
