### ISSUE TITLE
Frontend Initiatives Meeting : June 30, 2020

### ISSUE THREAD

**Issue by amcgee** [dhis2/notes#116]
# Frontend Initiatives Meeting

**When** : Tuesday, June 30, 2020 @ 15:00 CET
**Where** : remote, let me know if you didn't get a calendar invite

# Agenda
- Proposal Ratification
  - [PeerDeps for Singletons](https://github.com/dhis2/notes/issues/67)
  - [PeerDeps for wrapped external dependencies](https://github.com/dhis2/notes/issues/67)
  - [Release Strategy](https://github.com/dhis2/notes/issues/101) - slower, avoid major releases where possible, not **complete** until propagated
  - [Jira vs. GH Issues](https://dhis2.slack.com/archives/CDX5CE15W/p1592488981276700)
  - Managing workload and context switching (see below)

**Comment by ismay** [comment]
One thing that I've noticed lately (which might just be me), is that with our increased workload (with the plans we have for 2.35 + less people, etc.), plus a slight uptick in the amount of meetings and having to deal with changes in working conditions due to corona, it's become a lot more demanding to manage my focus. I'm not sure if it's something others are experiencing as well, but I thought I'd mention it. If I'm not the only one then maybe we could address it somehow.

**Comment by amcgee** [comment]
**Proposal: PeerDeps for Singletons**

Notably applies to `react`, `react-dom`, `styled-jsx`, `@dhis2/app-runtime`, `@dhis2/d2-i18n` (until deprecated), `@dhis2/ui` or `@dhis2/ui-core`. 

Always use peerDeps for things that MUST be singletons. Include these as dependencies in the app.

**Proposal: PeerDeps for wrapped external dependencies**

Notably applies to `prop-types`, `final-form`, and `react-final-form`

Leave as-is for now, wrap and re-export dependencies from libraries that are clear **extensions** of an external library. 
 However, plan a formal investigation into the advantages and challenges of moving to peer dependencies for a later major release (across libraries)

**Proposal: fewer, smaller major library releases**

Notably applies to `ui`, `ui-*`, `app-platform`, `app-runtime`, `d2-i18n`, and `analytics`

A few rules for major releases:
1. Any library release cannot be considered "complete" until it has been propagated to **every dependant library and app**.  Only at that point can Jira issues requiring changes to that library be marked complete and moved into testing.
2. Scope of major releases should be minimized - we should **not** combine many breaking changes into one release, and we should 
3. Breaking changes should be avoided, if possible, in favor of stability and API extensions.  Silent breaking changes (like renaming components or libraries and overloading a previously-used name) are forbidden unless absolutely necessary.  The goal is to fully understand the implications of a breaking change on **the entire DHIS2 ecosystem** before committing (and propagating) it.

**Discussion: Jira & GitHub**

Current situation and challenges:
1. Jira is **and will remain** the canonical place for user-facing changes in DHIS2, but is not configured in a way that makes it possible to track library issues yet.
2. GitHub has become the place for technical, developer-facing issues.  Library releases are not easily connected to application or core releases, however.
3. It is increasingly difficult to keep track of issues in multiple places
4. We do not currently have a solid mechanism for linking Jira and Github issues together
5. High-level visibility into development progress is somewhat obscured by having issues in GitHub without links to Jira

Some options (could be a combination of these):
1. Move everything to Jira, create new products and releases for every library and every application (we already will need a new one for each application).  Disable GitHub issues for all repositories not using them.
2. Set up synchronization between Jira and GitHub issues
3. Align versioning of libraries so that a release is cross-cutting and tracked in a single Jira project
4. Create a dashboard showing issues across all GitHub library repositories as well as Jira Issues (with links between them) and make it easy to maintain and visualize those links.

**Comment by varl** [comment]
My high-level take on JIRA / GitHub is this workflow. Note that this is incomplete in terms of details, however it should touch on all the important integration points.

### Objectives

- Use a single issue tracking system.
- Use vanilla features of the issue tracking system as far as possible because:
  - plugins add bloat to JIRA and leads to a slow JIRA instance,
  - and often breaks fundamental principles of how the JIRA data model works making filters hard to use properly.
- Not break things that work well with GitHub:
  - Low friction to add issues
  - Easy to add issues to the right place
  - Simple to track issues in releases and changelogs
  - Easy to get notified if an issue has been solved and/or released
  - Ability to have strong links between commits and issues
  - Ability to have strong links between pull requests and issues
  - Ability to have strong links between commits and pull requests
  - Ability to have strong links between issues and issues.
  - Ability to ignore those links in certain cases (e.g. cutting a release, updating deps)
  - Automatically create release and version metadata
- Everyone interacting with the issue tracking system **must** be able to work with it.

  >This may seem like a "duh" criteria, and in response to that, I offer [the extensive and simplified guide](https://github.com/dhis2/notes/issues/55#issuecomment-511761239) on how the Platform team uses JIRA.
  >
  > I have never had to write one for how to use GitHub.

###  On Git/Hub we:

- Disable issue tracking on GitHub all together.

- Update the [`.github/SUPPORT.md`](https://help.github.com/en/github/building-a-strong-community/adding-support-resources-to-your-project)[1] file to [refer people to JIRA](https://github.com/dhis2/.github/blob/master/SUPPORT.md)[2].

- In the `SUPPORT.md` we **must** include information on how to report issues correctly for apps and libs in JIRA.

- Update our `README.md` to refer people to JIRA as well, with a pre-filled [`createIssue` link](https://jira.dhis2.org/secure/CreateIssueDetails!init.jspa?pid=10406&issuetype=10006&summary=this%20is%20a%20test&components=10603&description=this%20is%20still%20a%20test&environment=foo&versions=10416)[3], e.g.:

```
https://jira.dhis2.org/secure/CreateIssueDetails!init.jspa
?pid=10406
&issuetype=10006
&summary=this%20is%20a%20test
&components=10603
&description=this%20is%20still%20a%20test
&environment=foo
&versions=10416
```

_(Line breaks added for readability)_

- Always include a JIRA issue id in our commit messages, the scope is the nicest option here as we would be able to generate very nice changelogs based on that format where we can target the same issue with multiple commits, i.e.:
  - `fix(hub-19): change behavior of xyz to match specs`
  - `feat(hub-19): add feature xyz baseline`

  This would allow:
  - the JIRA-GitHub integration we have to pick up the reference and automatically link the commit to an issue in JIRA,
  - and it allows our devs to use single-line commit messages,
  - and it works nicely with **conventional-commit** messages, 
  - and it works nicely with **semantic-commit**'s changelog generation,
  - and the changelog will also contain commits not tagged with an JIRA issue so it reflects the only source of truth; the commit log.

### On JIRA we:

- Create new projects for **LIBS** and **APPS**.

  - **DHIS2** will be reserved for Core.

  - **HUB** will be reserved for App Hub.

- Add relevant components in the relevant project:
  - **LIBS** gets components for e.g. `ui`, `platform`, `cli`.
  - **APPS** gets components for e.g. `maintenance`, `data-quality`, `data-visualizer`, `app-management`.

- Create simpler workflows for **HUB**, **APPS**, and **LIBS** where:
  - An issue can move from any state to any state.
  - Each state has required fields appropriate for that state.
  - Only the truly vital fields are visible in the **create** issue screen.
  - Optional information can be added later from the **edit** issue screen.

- Consider that "Planning" means to add a target version + internal rank:
  - So we get actual roadmaps for each version of each app and libs.
  - This is a "living plan" so it can change dynamically
  - That's why the internal rank is still of **utmost** importance to ensure that we are working on the "most important thing" for a version.
  - This way we get simple JIRA filters that we can use in our day-to-day work as developers to understand the picture on a micro and macro scale depending on the context we desire.

- Use comments to provide context why a given change was made.
  - It is common to provide updated information for an issue in a comment **and this is the WRONG way to do it**.
  - The issue description should be updated directly with the updated information, and a comment should be used to provide context for why the description was altered, for example, that the scope of the issue changed during development and was updated to reflect that.
  - Comments are for discussion, but when the information in a comment is so important that it changes the scope of the issue, that information **cannot** be buried in the comment; it must be in the summary and/or description !
  - JIRA remembers the history of all issues, so it is possible to go back and see what the issue originally was if that is a concern.

### Things not thought through _yet_

- Figure out how to ensure that tools that depend on GitHub Issues do not break, e.g.
  - **semantic-release** creates issues when a release fails
  - **dependabot** creates issues when something goes wrong
  - _others?_

- Do we keep issues open in `dhis2/notes` or do we migrate to a different system to track discussions and manage our decisions?

- JIRA projects are optimized for tracking a single project, so if we bundle all our libs into one project, using versions in JIRA to track versions becomes a nightmare and we basically have to create versions like: `cli-style@7.0.0` in JIRA to keep them apart.

- Versions in JIRA are not meant to be "light-weight"; they are manually created. Meaning that it is easy to screw up and can lead to versions in JIRA and e.g. NPM becoming out of sync. This needs to be automated somehow.

- When we publish a release using `cli-utils-release` we:
  - create a [release on GitHub](https://github.com/dhis2/app-hub/releases)[4] that contains the relevant changes from the [CHANGELOG.md](https://github.com/dhis2/app-hub/blob/master/CHANGELOG.md)[5] (which is **Great**),
  - and it adds a comment to all the referenced issues in GitHub Issues that the fix is included in the release (which is **Awesome**). 
  - Since we lose that comment on the included GitHub Issues, we should create a plugin for `cli-utils-release` that adds that comment to the referenced **JIRA** issue instead of the **GitHub** Issue.
  - The JIRA-comment-plugin should also update the `fixVersion` field to reference the version it is included in.

- The states in all our projects needs to "roughly" overlap so that they can be monitored by existing QA processes, e.g. `Open => In progress => Done` _could_ be enough if we have other ways to track e.g. when it moves from one team to another (e.g. from Analytics to QA for testing).

---

[1]: https://help.github.com/en/github/building-a-strong-community/adding-support-resources-to-your-project
[2]: https://github.com/dhis2/.github/blob/master/SUPPORT.md
[3]: https://jira.dhis2.org/secure/CreateIssueDetails!init.jspa?pid=10406&issuetype=10006&summary=this%20is%20a%20test&components=10603&description=this%20is%20still%20a%20test&environment=foo&versions=10416
[4]: https://github.com/dhis2/app-hub/releases
[5]: https://github.com/dhis2/app-hub/blob/master/CHANGELOG.md

**Comment by amcgee** [comment]
- [Meeting Recording](https://drive.google.com/file/d/1CPkBMWMy38iNu62K6FgiVYvANxmEw6mg/view)
- [Notes](#119)
