### ISSUE TITLE
Prioritization for ui issues

### ISSUE THREAD

**Issue by ismay** [dhis2/notes#125]
We discussed a couple of days back that we want to prioritize the dhis2/ui issue queue. I would personally prefer to keep the process (both the prioritization itself and this discussion) as simple as possible, so I'll just outline the core problem as I see it:

- Currently we don't prioritize, so there's no real telling which issue will or should be worked on next
- Our users don't know what to expect, and can't really give us feedback on what should be worked on and what they need
- We've had scope creep with releases due to our lack of planning: because there was no plan, PRs grew and grew until they became unmanageable

My preferred way to address this would be:

- We use github projects
- We prioritize issues with a small list of the most high priority ones in GH Projects (a big list would be demotivating), and maybe some further lists like medium and low priority, and unplanned
- Ideally we'd allow users to participate by say, upvoting the main comment (or commenting)
- Maybe a GH projects queue for the next major would be nice as well, just for allowing us to coordinate breaking changes

Now I'm not sure what the organizational requirements are here. Maybe GH Projects is off the table and we do the above in Jira. Which does seem more consistent with our other processes. In which case I would at least like a Jira component for UI (say [LIB] UI). Closing the GH issues completely seems good as well. Plus a prioritized queue like the one we currently have (team platform).

So my questions would be:

- Did I miss any problems we'd need to address (that relate to prioritization)? Or misunderstand what problems we want to solve?
- What would everyone's ideal solution be, and why? (probably best anwered once we agree on the problems)
- What are the organizational requirements? For example, is using Jira our only option, or does that not matter for the org?

**Comment by cooper-joe** [comment]
Thanks for bringing this up and starting the discussion @ismay.

> Did I miss any problems we'd need to address (that relate to prioritization)? Or misunderstand what problems we want to solve?

I agree with the three problems you highlighted. I might also add: there is no clear definition of what we are referring to with "issue". This could be bugs, new features, enhancements, etc. These different types of issues often require different types of input to resolve. Some may need project management input, some can be resolved by a single developer who is familiar with a component. I think clearly defining different types and what the process is for each needs to be part of this discussion.

> What would everyone's ideal solution be, and why?

Generally speaking, the ideal solution to me is the one that reflects the truth of what is being worked on/what is planned. I have a platform preference, but I am happy to work on any platform as long as the previous statement is true.

Other practical considerations:
- I think it useful to see an overview of what is going on right now, what is coming up next and the size of the backlog. A glance at those three gives me the info I need when working with/using `ui` in other apps.
- developer user feedback for bugs is valuable and should be encouraged with issue/bug templates to collect the information we need.
- I think a single "ui" project is enough, I don't think we should split into `core`, `widgets` and so on.

> What are the organizational requirements? For example, is using Jira our only option, or does that not matter for the org?

I cannot provide a definitive answer here. As far as I am aware all _products_  are managed in JIRA as this is the established product management platform for DHIS2. If we have good reasons to favor GH over JIRA I think we would need to present those reasons and get the sign off to go ahead on GH. 

I lean towards Github Projects here because it is closer to the source. On the other hand, the processes/workflows already set up on JIRA are very useful when used correctly and may help us to avoid monster-PRs by managing input/testing/reviewing through a different platform. I do not have a strong preference beyond finding Github easier to work with.

**Comment by ismay** [comment]
> I agree with the three problems you highlighted. I might also add: there is no clear definition of what we are referring to with "issue". This could be bugs, new features, enhancements, etc. These different types of issues often require different types of input to resolve. Some may need project management input, some can be resolved by a single developer who is familiar with a component. I think clearly defining different types and what the process is for each needs to be part of this discussion.

True. In my experience, _what_ route to take in resolving an issue has never really caused me much trouble. What _has_ caused me trouble is if an issue's scope is too large or too vague. In my opinion, as long as an issue describes a clearly isolated problem to be solved, it's something I can work with. I personally don't really feel like I need clear guidelines of the way to tackle each type of issue. I also think it would be quite hard to create those guidelines, and maybe a separate issue. But that's my opinion, would be good to know how the others feel about that.

> Generally speaking, the ideal solution to me is the one that reflects the truth of what is being worked on/what is planned. I have a platform preference, but I am happy to work on any platform as long as the previous statement is true.
> 
> Other practical considerations:
> 
>     I think it useful to see an overview of what is going on right now, what is coming up next and the size of the backlog. A glance at those three gives me the info I need when working with/using ui in other apps.
>     developer user feedback for bugs is valuable and should be encouraged with issue/bug templates to collect the information we need.
>     I think a single "ui" project is enough, I don't think we should split into core, widgets and so on.

Agreed, I feel the same way 👍

> I cannot provide a definitive answer here. As far as I am aware all products are managed in JIRA as this is the established product management platform for DHIS2. If we have good reasons to favor GH over JIRA I think we would need to present those reasons and get the sign off to go ahead on GH.
> 
> I lean towards Github Projects here because it is closer to the source. On the other hand, the processes/workflows already set up on JIRA are very useful when used correctly and may help us to avoid monster-PRs by managing input/testing/reviewing through a different platform. I do not have a strong preference beyond finding Github easier to work with.

Same here, that's how I feel about it as well 👍

**Comment by Birkbjo** [comment]
Thanks for the writeup, great initiative! I agree with many of your main points here, but I'm also worried about the fragmentation of using both Jira and GH-projects. Using GH-projects absolutely has it's benefits, but we have to keep in mind that our process is heavily based on Jira. This ties in closely with the frontend initiatives discussion in [June](https://github.com/dhis2/notes/blob/master/decisions/2020/06/30-frontend-peerDeps-and-releases.md). @amcgee started a great [initiative](https://docs.google.com/document/d/1AJxiNU1nJQxSPoC6BHsa8TkMaxLC85kbyQ9C8iaaUGQ/edit) to help support a hybrid approach of using jira and GH-projects. Unfortunately that has kind of been suppressed by summer and 2.35 release. Nevertheless, the results of that proposal will greatly impact the process that we are discussing here, so I believe many of the open questions would be answered once that is settled upon. That is not to say that we shouldn't discuss this here and now, but just something to keep in mind. 

I also think it's important to be able to prioritise from a higher level, so that we can identify UI-dependencies in more holistic issues. This would probably be team leads job as we sit in on these prioritisation meetings. In practice I think this would come pretty naturally by splitting a Jira-issue into GH-issues (or linking to sub-tasks).
I also think that we could use our weekly meeting as a medium to discuss prioritisation. Especially once we move to continuous releases this will be relevant for all our apps. The meeting should not turn in to a weekly prioritisation meeting, but maybe every six weeks or something we could put aside some time to go through issues etc.

As we discussed last week, we might want to align UI-releases with app-releases, and have releases on a regular basis. So it's also worth keeping in mind that we may move to a next-branch workflow again. I know that has caused some of the "big release"-problems previously, but I believe that more proper prioritisation would help keep the scope more succinct.

> I cannot provide a definitive answer here. As far as I am aware all products are managed in JIRA as this is the established product management platform for DHIS2. If we have good reasons to favor GH over JIRA I think we would need to present those reasons and get the sign off to go ahead on GH.

Agreed, and to me it's hard to specify a process here without first tackling the whole "library issue tracking"-problem, which is more of an organisational issue and not something we should try to solve for UI in isolation. At the same time, we need to start somewhere, but it needs to align with other processes.

**Comment by ismay** [comment]
Thanks for explaining @Birkbjo, really helps to have some perspective on the organizational side of things. 

> I'm also worried about the fragmentation of using both Jira and GH-projects. Using GH-projects absolutely has it's benefits, but we have to keep in mind that our process is heavily based on Jira.

Yeah I agree

> This ties in closely with the frontend initiatives discussion in [June](https://github.com/dhis2/notes/blob/master/decisions/2020/06/30-frontend-peerDeps-and-releases.md). @amcgee started a great [initiative](https://docs.google.com/document/d/1AJxiNU1nJQxSPoC6BHsa8TkMaxLC85kbyQ9C8iaaUGQ/edit) to help support a hybrid approach of using jira and GH-projects. Unfortunately that has kind of been suppressed by summer and 2.35 release. Nevertheless, the results of that proposal will greatly impact the process that we are discussing here, so I believe many of the open questions would be answered once that is settled upon.

I forgot about that, good point. Maybe it'd be good then to await results from that process, and then tackle this? Do we have a timeline for it?

> I also think it's important to be able to prioritise from a higher level, so that we can identify UI-dependencies in more holistic issues. This would probably be team leads job as we sit in on these prioritisation meetings. In practice I think this would come pretty naturally by splitting a Jira-issue into GH-issues (or linking to sub-tasks). I also think that we could use our weekly meeting as a medium to discuss prioritisation. Especially once we move to continuous releases this will be relevant for all our apps. The meeting should not turn in to a weekly prioritisation meeting, but maybe every six weeks or something we could put aside some time to go through issues etc.

I agree, both those points sound good to me. Would tie the process in with the organization more and could maybe create more awareness of the work that's being planned/done on our libraries. The higher up in the org. the discussion goes, the more high level I would expect the discussion to be. Maybe the leads could set out the more abstract, long-term goals for our libs explicitly, so that we have something to prioritize against.

> As we discussed last week, we might want to align UI-releases with app-releases, and have releases on a regular basis. So it's also worth keeping in mind that we may move to a next-branch workflow again. I know that has caused some of the "big release"-problems previously, but I believe that more proper prioritisation would help keep the scope more succinct.

I agree, clear scope sounds great. I hope we can make the planned releases for our libraries work, it's a bit of a novel concept to me. We've discussed it, and I understand what we're trying to solve, but maybe it'd be good to have the problem we're trying to solve with it absolutely clear. It feels slightly unconventional to me, or maybe I'm misunderstanding it.

> Agreed, and to me it's hard to specify a process here without first tackling the whole "library issue tracking"-problem, which is more of an organisational issue and not something we should try to solve for UI in isolation. At the same time, we need to start somewhere, but it needs to align with other processes.

Yeah I agree 👍

**Comment by ismay** [comment]
See also: https://docs.google.com/spreadsheets/d/1Gp1U0l8w6-GzmFmwtKpXYPur8712OV3xYiNtwKFw0ww/edit 

> Regarding prioritisation of ui issues: I spent some time today working through all the ui issues/tickets I could find on github and jira. This was mainly to refresh my own understanding of the state of the library, but I thought it might also be useful to document the design perspective I have from working across apps/teams.Prioritisation SpreadsheetI’ve added comments to explain the priority given, I hope these comments can help to inform the eventual prioritisation process. (From Joe)

https://dhis2.slack.com/archives/CBM8LNEQM/p1601469348008800?thread_ts=1600951861.024700&cid=CBM8LNEQM)

**Comment by amcgee** [comment]
One approach might be to implement a coordinated lib-app release lifecycle and workflow similar to [this proposal](https://docs.google.com/document/d/1LXi2-CeIAtZwTntFcVXC1EbaUT1oLL3CEqvqcqmAr_s/edit#heading=h.g9ebmh9wb0fg)

**Comment by varl** [comment]
I think this issue can be closed, as we are in the process of moving _everything_ into JIRA: https://github.com/dhis2/notes/issues/135
