### ISSUE TITLE
Cypress Meeting: November 10, 2020

### ISSUE THREAD

**Issue by varl** [dhis2/notes#139]
# Cypress Meeting

**Date**: 2020-11-10 @ 14:00 CET
**Open for all**: I invited a few reps from each team, but let me know if you want an invite!

Let us standardize on some practices across teams now that everyone is using Cypress for testing.

- Overwriting Cypress functions in general (https://github.com/dhis2/cli-utils-cypress/tree/master/packages/cypress-commands/src/commands)
- Helpers to make it easier to get a `data-test` selector?
- [data-test attribute as class names](https://github.com/dhis2/notes/issues/90)
- [data-test attribute naming convention](https://github.com/dhis2/notes/issues/88)

**Comment by martinkrulltott** [comment]
If we're discussing the use of `contains()` could we also touch on the subject for a custom "exact match contains" command? 👍

**Comment by Mohammer5** [comment]
Here are my thoughts on some issues, so everyone interested could think about it before we talk about it:

### Using data-test vs using content-based selector

This is a suggestion by @ismay to increase resilience to change (of underlying html structure).

I think there are quite a few cases where we can't use content-based selectors
* Checking how many rows have been rendered
* Checking if content exists that's display as an icon / non-text UI element (e. g. loading spinners)
* Finding content in a specific area (there might be scenarios where a sidebar contains text that's also in the main area, using a selector to limit the scope of a content-based selector would be helpful)

Generally speaking I think content based selectors are good and I have used them not often enough, but I can already see quite a few scenario where we'd have to use class/data-test selectors.

### Overwriting cypress commands

It's important to understand that we're extending them, not overwriting them! The `find` and `get` commands we've extended still call the original command. The reason why I like them is because it shortens selectors quite a bit while retaining their full functionality:

I can have selectors like this:
```css
{smscommand-commandlist-row}:first-child {smscommand-commandlist-isdefault}
```

which would look like this if I didn't use the special syntax:
```css
[data-test="dhis2-smsconfiguration-smscommand-commandlist-row"]:first-child [data-test="dhis2-smsconfiguration-smscommand-commandlist-isdefault"]
```

That makes it quite a bit harder to work on test code if it's full with very long selectors

**Comment by ismay** [comment]
With regards to the first point `Using data-test vs using content-based selector`. I think we should strive to follow the recommended order for selectors referenced in this article: https://kentcdodds.com/blog/making-your-ui-tests-resilient-to-change, which can be found here https://testing-library.com/docs/guide-which-query:

1. label
2. placeholder
3. text contents
4. alt text
5. title
6. display value
7. role
8. test ID

Note that test-id is at the very bottom. It is an option, but it's the last resort:

> Sometimes you can't reliably select an element by any of the other queries. For those, it's recommended to use data-testid (though you'll want to make sure that you're not forgetting to use a proper role attribute or something first).

His recommendations make sense to me. He's an experienced developer, his arguments make sense and I don't see why we wouldn't follow his guidelines as well. I don't think we should be making using a data-test id any easier. It's good if there's a little friction, and I don't think the current methodology of selecting is _that_ bad anyway, it's just standard selector syntax.

# Extending cypress commands

See the argument made above. I don't think we should be making the use of data-test selectors any easier. That'll just make it easier to go straight to our least preferred option, which is not something I think we should be incentivizing. If anything I think we should revisit and tone down our usage of data-test selectors.
