### ISSUE TITLE
Unified form handling

### ISSUE THREAD

**Issue by Mohammer5** [dhis2/notes#25]
Ok.. So this is kind of two things in one:

## Form handling in the UI library
It would be very nice to have components that unify how we handle forms. If we agree on a way, it'll be a long way to implement these new components (especially in the maintenance app), but it'll make building/working with forms much, much, much easier!

## Using react-final-form
This is the successor of redux-form. It's bundle size is much smaller, it has plugin capability and a very nice feature-set.

# Both topics together
The reason why I started one issue for both topics is that react-final-form is very nice but it's still a tedious process to get everything else up and running, like styling the form, using MUI components, etc.
Although having components for a form has way less text in this issue, it's much more important than using final-form.
It would be very nice to have components ready for Inputs, Selects, Multi-Selects, File Uploads, TextAreas, Form sections (with headlines), Form Dialogs, and some way to compose validation with smaller validation functions.

**Comment by varl** [comment]
@Mohammer5 could you split your post in twain so the description only relates to the topic and any relevant facts like alternatives, and post your personal experience in a separate comment?

Also, update the issue title to "Unified form handling" to make it more general as there are more ways to handle forms than react-final-form.

Some of the alternatives which need to be addressed:

- `redux-form`
- `@dhis2/d2-ui-forms`
- `react-final-form`

**Comment by Mohammer5** [comment]
Here's my personal experience with react-final-form so far:

I think for a good UX, it's very important to show good error messages (and to show them at the right time and all of them, so you don't have to submit a form multiple times and fix one error for every submit). Forms can easily bring a react/redux app to it's knees.. as you have to validate on every keystroke while keeping in mind which fields have been touched/visited/etc.

#### Provides input meta data
React-final-form has all the info at hand.. You can access the error, dirty, touched properties without having to worry too much about that stuff. In fact you have control over almost everything. 

#### Easy to hook into functionality
I was just working on a file input where I needed to read the file contents when submitting the form instead of just uploading the file. React-final-form provides format/parse properties so you can easily handle that (in my case parse wasn't the right thing, so I just hooked into the onChange functionality on the input field and it just worked easily).

#### Nicely formatted data
Multi-Select and multiple checkbox values are collected in an array

#### Validating data
It's ridiculously easy to validate fields that depend on other fields. You can pass a validate function to the form and create an error object that contains all the errors which will be displayed on all touched inputs.
Submitting a form will turn all inputs into touched inputs.

#### Can be twisted to handle performance critical forms
If forms contain 20+ (maybe 50 or 100) inputs, it's very hard to get it right. react-final-form provides functionality to reduce the amount every single input has to render to it's minimum if this is required. It's a bit more work but still quite straight forward.

**Comment by varl** [comment]
>It would be very nice to have components ready for Inputs, Selects, Multi-Selects, File Uploads, TextAreas, Form sections (with headlines), Form Dialogs, and some way to compose validation with smaller validation functions.

This is out-of-scope for the dhis2/ui library, but the component primitives exposed by the core ui library should be used to build up those components and utility features such as validation.

We have the `d2-ui-forms` package today, which is ... not great ... to use, so let's not use that, but rather rebuild the package into one that pulls in dhis2/ui and `react-final-form` and exposes everything a developer of DHIS2 apps needs to do forms in a standardized and easy-to-use way.

I know dhis2/d2-ui is merging back to one package, though that just makes it more important that we replace the forms implementation with one that we are happy with using.

**Comment by varl** [comment]
cc: @dhis2/dhis2-front-end 

Pinging all frontenders, your expertise on forms is necessary here! :)

**Comment by ismay** [comment]
> Some of the alternatives which need to be addressed:

> redux-form
> @dhis2/d2-ui-forms
> react-final-form
 
I’d be interested in weighing our options as well. I think in order to make a good choice it’s nice to have a high level overview of what we need, what trade offs we’d be making, maybe some links to posts about other people’s experiences, comparisons, etc.

**Comment by varl** [comment]
> I’d be interested in weighing our options as well. I think in order to make a good choice it’s nice to have a high level overview of what we need, what trade offs we’d be making, maybe some links to posts about other people’s experiences, comparisons, etc.

Feel free to post!

I found the discussion @Birkbjo, @HendrikThePendric, and @erik, weighed in on September 28 2018 on Slack.

### Links

- "Next Generation Forms with React Final Form": https://www.youtube.com/watch?v=WoSzy-4mviQ
- Formik vs. Final Form: https://github.com/jaredpalmer/formik/issues/533

### Quotes

@Birkbjo on `redux-forms`:
>I tried redux-form in the appstore, and that is great and very powerful.  However then we lock in to redux for everything, and it can be quite heavy I guess (28kb gzipped and the whole redux pipeline for every change).

@Birkbjo on the built-in form handler in maintenance (similar to d2-ui?):
>I’m quite tired of all the bugs, hacks and performance issues with the FormBuilder, might be just the maintenance app - but its so annoying.

@Birkbjo on `redux-form` vs. `react-final-form`:
>The same maintainer created react-final-form. It seems more lightweight, with a lot of the same capabilities. The only reason to use redux-form over it is if we need to change the values given to the form from other places via actions. And that does not seem to really be an use case we would need.

**Comment by Mohammer5** [comment]
@varl @Birkbjo 
Very interesting! I haven't tried redux-form, but I have the same good experience with final-form.

### What functionality do I think we need

#### 1. Easy validation & error handling/display
Form validation in maintenance app is hell... Collecting errors manually is a tedious process as well.
To me there are two scenarios that need to be taken into consideration:

1. Smaller forms
If we could just pass a function to the form component that checks all fields and returns an error object,
that'd be perfect. No more hassle about storing the error state somewhere, should be handled entirely by the form component.

2. Larger forms (50+ fields)
In this case the validation needs to happen on field level, I think(?). So here it'd be nice to just pass a validation function to the individual fields that has acces to the current field value & name as well as all values.
To make it nicer to work with, we could introduce some commonly used validation functions (`isRequired`, `isValidEmail`, `isSecurePassword`, `applyValidationsIf`, etc) and a composition mechanism (similar to using pipe/compose so that each validation function receives the three values and returns either a falsy value or the error message as string).

Ideally we use the validation functions to compose the one validation function for smaller forms,
here's some pseudo code (don't take this code too serious, it's just a sketch):

```js
const validate = values => {
    let error
    const errors = {}

    if (error = validateName(values)) errors.name = error
    if (error = validateEmail(values)) errors.email = error
    if (error = validateEmailVerification(values)) errors.emailVerification = error

    return errors
}

const validateName = values =>
    isRequired(values.name)

const emailValidators = [
    isRequired,
    isValidEmail,
]
const validateEmail = values => applyValidator(
    emailValidators,
    values,
)

const validateEmailVerification = values => applyValidator(
    [
        ...emailValidators,
        applyValidationsIf(
            values => values.email,
            matchesField('email'),
        )
    ],
    values,
)
```

#### 2. Unified styles
To me it seems that forms look different from app to app. I guess this is quite self explanatory.

#### 3. No need to think about styling anymore
Everyone hates building forms I guess.. so I'd like to get this done asap. Having to write & apply styles for headlines, error/hint text size/color, form sections is very annoying and is a major reason why forms look different across all apps!
Also creating a layout for a form costs a lot of time. If we had some "code-ified" guidelines/standards, it'd be easy to apply without having to think about them (expect for "which section does this field belong to")

**Comment by Mohammer5** [comment]
Does anyone have experience with Formik?

**Comment by varl** [comment]
... Oh man, the code base of `react-final-form` and `final-form` _together_ is so much nicer to read than `redux-form`.

**Comment by HendrikThePendric** [comment]
I agree with almost everything being said here. Below is a summary of my thoughts:
- I loved Redux-form, but React Final Form is even nicer, so I would love to start using it in our apps

- It would be great to have to have a set of shared components that conform to the REDUX form API

- I agree that the current UI form components should be used as a base for the form components that can be used directly by React Final Form

- I'm not sure that `d2-ui` would be the repo to keep these. Perhaps this grants a separate repo, because these are going to be artefacts that are tied to a specific form framework, while I think the d2-ui components should be of a more general nature. 

- Reg. validations (1), and thinking mainly about the maintenance app v2: it would be great if we have an extensive set of validation functions, and we use the schemas to automatically bind the right ones to a form-field. Perhaps this could be a higher-level component `d2-metadata-form`....

- Reg. validations (2): I think the pseudo code examples @Mohammer5 provided are an example of **form-level validation** (i.e. 1 validation function for all fields). In the user-app, which uses redux-form (with a very similar API to final-form), I recently refactored all my forms to use **field-level validation** (i.e. specify validators per field component). This made everything a lot easier to reason about. Final Form has this distinction between form and field-level validations too, we should go with [field-level validation](https://codesandbox.io/s/k10xq99zmr) from the start.

- Reg. redux-form as an alternative: I've worked with Redux form a lot, and really like it. One thing I don't like is the fact that a form can get pretty heavy on the re-renders very easily. There are ways around it, but I think the way FinalForm allows you to [control this via subscriptions](https://codesandbox.io/s/32r824vxy1) makes a hell of a lot of sense 🎉. Another problem with redux-form is async field validation. This is completely separate from the sync-validation, and has a quirky API. In React Final Form sync and async validations are treated [pretty much the same](https://codesandbox.io/s/wy7z7q5zx5), so this is excellent.

- Reg. Formik: when @varl, @Birkbjo  and I were discussing form libs a few months ago, I did read up on the Formik API. It didn't make much sense to me, and I discarded it as an option pretty quickly. I don't think I gave Formik a fair shot, because I was already pretty comfortable working with redux-form at that point, and React FinalForm has a very similar API. So I was probably completely biased towards the more familiar. It would be good if someone else, with an equal level of (in)experience in both libs reviews both FinalForm and Formik.

**Comment by varl** [comment]
I think there is room to have something like these packages:

- ui-core
- ui-widgets
- ui-forms
- ui-i18n

_* still trying to get away from the `d2-` prefix_

**Comment by Mohammer5** [comment]
UPDATE: So there now exists a [JIRA issue](https://jira.dhis2.org/browse/TECH-157) for creating the `ui-form` lib.
As discussed in the meeting yesterday, we'll need to talk about implementation details of the new library.

## My current thoughts

#### Form inputs
* **These inputs should reside in `ui-core`** so they can be reused regardless of how we handle form submission, validation, etc.
* **They are not opinionated**, so they can be used in any context as long as react is the underlying rendering lib
  * **They expected the same props as normal input components** (value, name, onBlur, onChange, etc) so that they could be used interchangeably
* This is also the same for complex form inputs, like the org unit tree

#### Form handling
* **The whole form handling will be done in `ui-form`** as this is clearly opinionated.
* **The `ui-form` lib should provide composable validator functions for single fields**, so you can easily say "This field is 1. required and 2. needs to be a valid e-mail address" as well as "This field is 1. required when field 'foo' has the value "ABC" and 2. is a secure password and 3. does not contain more than x character"

## What I'm not sure about

#### 1. Where to put form sectioning/styling components
I'm talking about components like form sections, form headlines, form pages. Right now I think they're part of `ui-core` as well.

The `ui-form` lib will have to make sure that the first page with an error is shown when there are form errors (otherwise the user will have to search for the input field which is frustrating).

#### 2. props interface of inputs
When using the render prop of react-final-form's `Field` component, it looks like this:
```jsx
<Field
  name="name"
  type="text"
  render={ ({ input, meta }) => <input {...input} /> }
/>
```

But they can also be done like this:
```jsx
import Input from '@dhis2/ui-core/Input'

<Field
  name="name"
  type="text"
  component={Input}
/>
```

@HendrikThePendric mentioned that it'd be nice if we could just pass our `ui-core` components to the `component` property, which would be very nice! At the time he mentioned that, I thought that out components would need to expect a `input` and `meta` property. Right now, I'm not so sure, it might very well be that react-final-form already spreads the "input" property for us.
=> I will create a codepen to check out how this works, as I'm still not certain how the component would receive the `meta` prop

#### 3. Specification of what the lib should be able to do
I'd really like to test the three following technologies in combination:
1. Cypress
1. [Cypress + Gherkin](https://www.npmjs.com/package/cypress-cucumber-preprocessor)
1. [Cypress + Storybook](https://medium.com/@mtiller/testing-react-components-using-storybook-and-cypress-1689a27f55aa)

This would mean we could test components in isolation with gherkin specs without having to rely on selenium, writing test should be pretty straight forward, and we'd have 1. specification, 2. documentation and 3. tests

I'd like to achieve the following: 
1. I want to make sure that things are aligned properly (which can only be done with real DOM)
1. I want to make sure that spacing is correct (which can only be done with real DOM)
1. Have proper docs and tests that don't need to be maintained additionally (creating specs means adding docs and tests)

Using gherkin I could just write a few specs down that I have in mind without having to create a JIRA issue for each of those. We can then assign groups of specs to one JIRA issues to get them done iteratively.

**Comment by Mohammer5** [comment]
Ok, I have added an example of what props the component passed to the `component` prop receives:
https://codesandbox.io/s/pwzv0xpjnx

It gets the `input` prop, react-final-form does not spread `props.input`.
This means that we can't do this:

```js
import Input from '@dhis2/ui-core/Input'

<Field
  name="name"
  type="text"
  component={Input}
/>
```

We have to do this:
```jsx
import Input from '@dhis2/ui-core/Input'

<Field
  name="name"
  type="text"
  render={({ input, meta, ...rest }) => (
    <Input {...input} {...meta} {...rest} />
  )}
/>
```

To me this is perfectly fine, as I want to keep the `Input` component in `ui-core` unopinionated.

**Comment by Mohammer5** [comment]
I think it's good practice to use the same name conventions that react-final-form uses in our `ui-core` library though:

```
const inputPropTypes = {
  name: propTypes.string.isRequired,
  value: propTypes.string.isRequired,
  error: propTypes.string,
  touched: propTypes.bool,
  visited: propTypes.bool,
  .....etc
}
```

**Comment by varl** [comment]
> I think it's good practice to use the same name conventions that react-final-form uses in our `ui-core` library though:

Could you expand on this a bit? Coupling the `ui-core` components to an API of a peripheral package does not immediately seem like good practice to me?

**Comment by Mohammer5** [comment]
> Coupling the ui-core components to an API of a peripheral package 

That's not what I want to do.
The `input` prop that's passed to the component rendered by `Field` contains this:
```
name
value
onBlur
onChange
onFocus
```

The `meta` prop that's passed to the component rendered by `Field` contains this:
```
active
data
dirty
dirtySinceLastSubmit
error
initial
invalid
modified
pristine
submitError
submitFailed
submitSucceeded
submitting
touched
valid
visited
```

So what I wanted to propose is that our input's use the same terminology, like so:
```jsx
const Input = props => { .... }
Input.propTypes = {
	name: PropTypes.string.isRequired,
	value: PropTypes.string.isRequired,
	onBlur: PropTypes.func,
	onChange: PropTypes.func,
	onFocus: PropTypes.func,
	active: PropTypes.bool,
	dirty: PropTypes.bool,
	dirtySinceLastSubmit: PropTypes.bool,
	error: PropTypes.string,
	initial: PropTypes.string,
	invalid: PropTypes.bool,
	modified: PropTypes.bool,
	pristine: PropTypes.bool,
	submitError: PropTypes.bool,
	submitFailed: PropTypes.bool,
	submitSucceeded: PropTypes.bool,
	submitting: PropTypes.bool,
	touched: PropTypes.bool,
	valid: PropTypes.bool,
	visited: PropTypes.bool,
}
```

To clearify this:
* I **don't** want to change our `Input` in such a way that it's compatible with react-final-form
* I want to use their prop names as they make a lot of sense and seem offer a good interface for almost all states an input can be in

**Comment by ismay** [comment]
Broadly speaking I like the suggestions made in this thread. One thing that worries me a bit on a more general level is this suggestion:

> The ui-forms could make use of those components and provide a more sophisticated and opinionated api like a FormRow components and built-in react-final-form handling.

This sounds a bit like an abstraction that could become annoying and cumbersome to maintain very quickly. I'm not sure what the proposed api / use case is here, but I think we should be careful to not over-abstract. I'd start with the basic low-level components, and then after a while see if there is a need for more high-level abstractions.

I think if there's one I see all over our codebases that causes problems (for me) it's premature abstractions.

**Comment by HendrikThePendric** [comment]
**Reg. what @Mohammer5 wrote:**
> Ok, I have added an example of what props the component passed to the `component` prop receives:
> https://codesandbox.io/s/pwzv0xpjnx
> 
> It gets the `input` prop, react-final-form does not spread `props.input`.
> This means that we can't do this:
> 
> ```js
> import Input from '@dhis2/ui-core/Input'
> 
> <Field
>   name="name"
>   type="text"
>   component={Input}
> />
> ```
> 
> We have to do this:
> 
> ```js-jsx
> import Input from '@dhis2/ui-core/Input'
> 
> <Field
>   name="name"
>   type="text"
>   render={({ input, meta, ...rest }) => (
>     <Input {...input} {...meta} {...rest} />
>   )}
> />
> ```
> 
> To me this is perfectly fine, as I want to keep the `Input` component in `ui-core` unopinionated.

I'm not quite sure how you reached that conclusion. In the `reports-app` we are assigning our form components to the `component` of the react-final-form `Field` component. All props added to a `Field` are passed through to the form-component. Maybe there are some shortcomings I am not aware of....

---
**reg. the repos**
Building on, and disagreeing a little with what @varl wrote, I see these repos working together:

`ui-core`
This contains the lowest-level form-components with generic api and correct styles

`ui-widgets`
This contains some more complex form components such as org-unit-tree, etc.

`final-form-components` or `final-form-fields`
This repo imports components from both `ui-core` and `ui-widgets` them compatible with `react-final-form`. The definition of compatible, in my mind, would be that usage like this would work:
```javascript
<Field
    name="meal"
    component={SelectField}
    options={meals}
    value={selectedMeal}
/>
```
Because this repo is going to provide bindings specifically for `react-final-form` I think this should be made clear in the repo name, and `ui-forms` would be too generic.

`validators`
This could be a place where generic validation functions live, `email`, `password`, `phone`, `positiveInteger` etc. I'd like to keep this out of the `final-form-components`, because these are not tied to final-form. A bit besides the points, but this could also be an opportunity to consolidate some of the validation stuff we already have, i.e.:
https://github.com/dhis2/d2-utilizr/tree/master/src
https://github.com/dhis2/d2/blob/master/src/lib/check.js
https://github.com/dhis2/d2-ui/blob/master/packages/forms/src/Validators.js
(Quite likely there are more to be found)

**Comment by Mohammer5** [comment]
@HendrikThePendric 
We've built the input components in a way so that it's possible:
https://github.com/dhis2/reports-app/blob/master/src/components/form/Input.js

When you look at the prop types, we're expecting `input` and `meta`, which is not how you'd normally architect prop types for input components. I wouldn't like to go that way either for components in `ui-core` as they'd be opinionated and tied to the react-final-form api

**Comment by Mohammer5** [comment]
> This sounds a bit like an abstraction that could become annoying and cumbersome to maintain very quickly. 

@ismay I haven't really thought about what the `ui-form` would look like so far, which is why I'd propose to do the following:

I'll create the repo, get the cypress/gherkin/storybook stuff working on the master branch and then create gherkin feature specs that can be discussed/changed in a PR before they become part of the master branch. Once we've reached a conclusion what the mvp could look like, we can start implementing that as well.

I'd like to have everyone of tapps on board when it comes to deciding what should be inside the repo and what shouldn't be so get an optimal UX and DX

**Comment by Mohammer5** [comment]
> I'll create the repo, get the cypress/gherkin/storybook stuff working on the master branch and then create gherkin feature specs that can be discussed/changed in a PR before they become part of the master branch. Once we've reached a conclusion what the mvp could look like, we can start implementing that as well.

@varl We could add this to an app shell for ui libraries if this turns out to be working nicely?

**Comment by amcgee** [comment]
I think codifying a form library is a great idea!  However, I think the **api** of that library should hide the **implementation detail** that it uses `react-final-form` under the hood.  It's important to think of how this will be used in an application.  Here's one concocted example of a multi-page Wizard - I'm making a lot of stuff up here, but importantly there's nothing final-form specific.

```js
import { Form, 
               Page as FormPage,
               TextField, 
               FieldRow, 
               DateField, 
               SelectFIeld, 
               CheckboxField, 
               SubmitButton, 
               isRequired, 
               isValidEmail
             } from '@dhis2/ui-form'

const MyForm = () => {
  <Form onSubmit={values => alert(values)} onPageChange={() => console.log('page changed')}>
    <FormPage>
      <TextField name="name" label="Name" required={true} /> {/* required is an optional convenience alias for validate={isRequired} */}
      <TextField name="email" label="Email" hintText="Type a valid email" validate={[isRequired, isValidEmail]} />
      <FieldRow> . {/* Like @ismay I'm not sure I like this, seems easy to break */}
        <SelectField name="type" label="Character Type" options={[{ hero: 'Hero', villain: 'Villain']} defaultValue={'villain'} />
        <CheckboxField name="stealth" label="Stealth Mode" defaultValue={false}
      </FieldRow>
  </Page>
  <Page>
      <h1>You are ready to go!</h1>
      <Checkbox name="terms"
          label="I will not sue the company if my character dies"
          defaultValue={false} validate={value => !!value || 'You must promise not to sue!'}
       />
      {/* this demonstrates a custom error message resulting from a validation failure. 
           It is delegated to the presentational component to render this error message. */}
      <SubmitButton label="Blastoff" />
  </Page>
</Form>
```

Each of the `<*Field>` components would transparently wrap the purely-presentation and form-unaware presentational component from `ui-core` like `TextBox`, etc.

(side note: for another project I build a Wizard wrapper around `react-final-form` which does page-level validation rather than field- or form-level, happy to generalize that if it's useful) 

We **might** want to expose a primitive `<Form>` wrapper which could wrap any arbitrary UI, though this somewhat breaks the abstraction and should be a rare exception - if we need to use it all the time, we've failed to create a flexible-enough API:

```js
<CustomField name="custom">
  ({ input, meta }) => (
    <MyCustomFieldComponent {...myFancyLocalProps} {...input} myCustomError={meta.error} />
  )
</CustomField>
```

The `input` and `meta` parameters could pass directly through from `react-final-form`, or we could extend them.  Note that there's no need to proxy unknown parameters (and therefore no possible prop name conflicts with `name` etc) because you can rename props in the child-render-function.

This would technically work with a `render`-prop pattern, but I prefer the `render`-child, it feels cleaner to me.

My 2c - generally very in favor of creating a generalized form-handling abstraction layer!

**Comment by varl** [comment]
>I think the api of that library should hide the implementation detail that it uses react-final-form under the hood. If we use that pattern, the library name shouldn't have anything to do with react-final-form and I like @dhis2/ui-form as a general-purpose form container.

I agree with this and consider it a good design principle for all of our libraries as well; e.g. `d2-i18n` should also not leak the `i18next` implementation (which it does today).

**Comment by HendrikThePendric** [comment]
@varl & @amcgee I think what you are talking about is very different from what I had in mind:
1. I was thinking about providing "FinalForm bindings" for our form components. The app would be using `react-final-form` directly and it would be easy to use our form-components as the presentation part of a `react-final-form` `Field`.
2. You are suggesting to build a form lib that uses `react-final-form` under the hood

IMO 1 is a much more flexible approach. We've tried the second approach already, and I don't think it was very successful.

**Comment by ismay** [comment]
I'd be interested in what the first approach would look like. For an app implementing these "FinalForm bindings", could you sketch out some pseudo code so I can get an idea of the implementation?

I'm also leaning towards 1. Seems more flat and simple.

**Comment by Mohammer5** [comment]
@HendrikThePendric and I talked about this. Once I understood what he meant I really liked his idea.
I still have some concerns (which doesn't mean I'm against the idea, it just means we'll have to discuss it), which I'll address after an example of what Hendrik thought about:

So his Idea is basically to have a `Input` component (and other form components) in `ui-core`. The `ui-final-form-bindings` will wrap the `Input` and expose a component called `Input` itself as these components need to expose a different prop api.

That way we can do the following in our apps:

```jsx
import { Form, Field } from 'react-final-form'
import { Input } from 'ui-final-form-bindings'

export const LoginForm = props => (
    <Form
        validate={validateLoginForm}
        onSubmit={props.onSubmit}
    >
        {({ handleSubmit }) => (
            <Field name="name" component={Input} validate={notEmpty} />
            <Field name="passwort" componen={Password} validate={notEmpty} />
        )}
    </Form>
)
```

After having use react-final-form, I now know that when having multiple checkboxes or radio buttons, each of these checkboxes will need to be wrapped with a `Field` component. So either we'll have a CheckboxGroup component in `ui-core` that accepts a component as well, so we can do:

```jsx
import { Checkbox, CheckboxGroup } from 'ui-core'
import { Field } from 'react-final-form'

const PizzaIngredients = props => (
    <CheckboxGroup
        groups={pizzaIngredients}
        component={(name, value) => (
            <Field name={name} value={value} component={Checkbox} />
        )}
    />
)
```

Alternatively we can have that component in `ui-final-form-bindings` instead of `ui-core`, but that would defeat the purpose of having not-opinionated components in ui-core and all other ui libs will make use of those.

The other thing I'm wondering about is how to implement form wizards (multiple pages) with per-page-validation. I've researched a bit how to do this with react final forms and found out that each page needs to be a form while the main form needs to keep track of the values with final-form's [`FormSpy` component](https://github.com/final-form/react-final-form#formspy--reactcomponenttypeformspyprops)

This would not match the structure of the library to be flat and just wrap the input components so we can use react-final-form in the apps itself, we'll definitely need to use this also in our `FormWizard` component, if we want to offer such an component (which will definitely be reused if we had one, the maintenance app has billions of those forms). Should this be a separate ui lib? Should we not do this at all?

**Comment by HendrikThePendric** [comment]
I've discussed things a bit more with @Mohammer5 as well, and changed my original idea slightly. My original idea would be a bit like this:
```javascript
import React from 'react';
import PropTypes from 'prop-types';
import i18n from '@dhis2/d2-i18n';

import { Form, Field } from 'react-final-form';
import CheckBox from '@dhis2/final-form-fields';
import Input from '@dhis2/final-form-fields';
import Select from '@dhis2/final-form-fields';

const Component = props => (
    <Form onSubmit={props.onSubmit}>
        {({ handleSubmit, values }) => (
            <form onSubmit={handleSubmit}>
                <Field
                    name="name"
                    placeholder={i18n.t('Name')}
                    component={Input}
                    value={values.name}
                />

                <Field
                    name="gender"
                    placeholder={i18n.t('Gender')}
                    options={['Male', 'Female', 'Something else']}
                    component={Select}
                    value={values.gender}
                />

                <Field
                    name="newsletter"
                    placeholder={i18n.t('Please spam me')}
                    component={Checkbox}
                    value={values.newsletter}
                />
            </form>
        )}
    </Form>
)
```
Initially, I would like to work towards a situation in which we are always using the `react-final-form` (RFF) `Field` component directly, and assign our "form-bindings" to `component` property of the RFF `Field`.

However, @Mohammer5 pointed out some situations where it could be beneficial to have components that render `Field`s internally. A good example is a `CheckBoxGroup`, it makes a lot of sense to pass it a name and a list of values, and a name, and let it render `Field`s that use the `CheckBox` for its `component` prop.

We could follow this approach for all components, so the example above would now look like this:
```javascript
import React from 'react';
import PropTypes from 'prop-types';
import i18n from '@dhis2/d2-i18n';

import { Form } from 'react-final-form';
import CheckBox from '@dhis2/final-form-fields';
import Input from '@dhis2/final-form-fields';
import Select from '@dhis2/final-form-fields';

const Component = props => (
    <Form onSubmit={props.onSubmit}>
        {({ handleSubmit, values }) => (
            <form onSubmit={handleSubmit}>
                <Input
                    name="name"
                    placeholder={i18n.t('Name')}
                    value={values.name}
                />

                <Select
                    name="gender"
                    placeholder={i18n.t('Gender')}
                    options={['Male', 'Female', 'Something else']}
                    value={values.gender}
                />

                <Checkbox
                    name="newsletter"
                    placeholder={i18n.t('Please spam me')}
                    value={values.newsletter}
                />
            </form>
        )}
    </Form>
)
```

However, what is **MOST IMPORTANT TO ME** is that we are able to freely mix form-components from the`@dhis2/final-form-fields` with form-components that are created specifically for the app. So effectively, to me, that would mean:
- Our form-components can work as direct descendants of a RFF `Form`
- Our form-components have an API that is a super-set of the RFF `Field` component
As such, I don't think that in this case it makes sense to abstract away the fact that we are using RFF. The components we offer are supposed to be used with that lib specifically.

The reason I would prefer this approach is that I don't want to end up in a situation where we have to add a new form-field component to our lib every time we encounter a new situation. I am afraid that if we head into the direction of offering a full-blown form lib, this is where we will end up. Just introducing some form-field component that can be used in a RFF feels like a much more lightweight and flexible solution to me....

**Comment by amcgee** [comment]
@HendrikThePendric, @Mohammer5, and @ismay - important considerations, thanks for sharing them here!

Regarding @HendrikThePendric's **MOST IMPORTANT** point - I believe this can be accomplished with a Form abstraction layer that uses RFF internally with the `<CustomField>` component I mentioned - usage in a previous comment.  This would allow the library to be extensible in the exception cases (which I agree we should support rather than requiring a million variable components in the Form library, but also think we should try to limit).

Like @HendrikThePendric I think the wrapped input should include the `Field`, not the other way around.

I agree that a light-weight `<Field>` wrapper is simple and straightforward, but I would argue that a lightweight `<Form>` wrapper **does not** significantly increase complexity but **does** significantly increase the consistency of form handling across forms throughout DHIS2 applications.

We should aim to provide a consistent form input experience - initially that can be a thin wrapper around RFF Form and Fields (of various types) with some built-in extensions like a multi-page form Wizard which would be difficult to do without wrapping the RFF `<Form>` - I'll clean up and share my working implementation of this, in case it's helpful.

My main concern with building a library **peer-coupled** to RFF (like `ui-final-form-bindings`) is that the use of RFF proliferates throughout our many codebases, inevitably (1) getting out of date, (2) missing the latest features we implement in the form library because it's a big lift to update the usage all over, (3) having a breaking change in RFF break our bindings and causing us to fork those bindings or leave them broken (a la `d2-ui` and `material-ui` circa 2017, I think), and (4) deciding we don't wan t to use RFF in core apps any more and realizing we have 15 different apps relying on 5 different RFF versions to upgrade.  In the abstracted library case (`ui-form`) we can seamlessly upgrade or replace RFF in one place and maintain consistent Forms across the ecosystem.

---

One of our design goals for DHIS2 applications should be to minimize the number of required dependencies.  If we're moving towards consistent form handling, we should provide form handling as a "built-in" feature of our application platform.  Internal to the platform this should be modular with good functional separation-of-concerns, and it could even be opt-in from the application side (i.e. `ui-form` is provided by default but use your own form library but our `ui-core` input components if you want) but **opting in to the standardized DHIS2 application platform should not add an external requirement to applications**.  Auxiliary functionality (for instance Auth0 authentication for external services) should be provided in the `bindings` model, but form handling is a core piece of the application platform in my mind.

---

I don't think what we're each talking about here is all that different under the hood - the components are pretty much identical and I'm just advocating for a thin wrapper around the `<Form>` as well with an RFF-agnostic (though possibly matching) API so we can provide consistent extensions and sensible defaults in one place.

**Comment by varl** [comment]
We have to own the external API for the libraries which are the foundation for DHIS2 developers. Not just for our sake, but for the sake of all DHIS2 developers who trust and rely on our decisions.

---

>The reason I would prefer this approach is that I don't want to end up in a situation where we have to add a new form-field component to our lib every time we encounter a new situation. I am afraid that if we head into the direction of offering a full-blown form lib, this is where we will end up.

Yes, but this is a good idea for the same reason `ui-core` is a good idea. We could have gone with `material-ui` or `styled-components` in `ui-core` as well for the same reason as above, but they are leaky abstractions and would expose the fact that we use MUI or styled-components components under the hood and that is a worse situation than investing in a API which we control.

The reasons @amcgee outlined, 3 and 4 _especially_, are very important to the long-term health of the entire ecosystem of developers and apps -- _not just our 40 internal apps, but also all the external applications_.

>Just introducing some form-field component that can be used in a RFF feels like a much more lightweight and flexible solution to me....

You are right, it is more lightweight and more flexible. It is faster to get started with it, and less work is required up front.

The other side of that coin is that maintenance gets a lot harder because instead of a straight dependency to a single library we again have to manage that our app uses the right version of bindings which work with the right version of react-final-form.

We see it in `d2-i18n` too. It just passes through the entire API from i18next, which causes an indirect coupling between the application and i18next. Say that we want to change the API for `d2-i18n` now. How do we do that?

We see it in `d2-ui` where the components returned are actually MUI components. Now the apps are using them as MUI components with other MUI components. And it works because our components _are_ MUI components. But if we change something in the API all those assumptions break.

It began lightweight and flexible; now it's a liability.

**Comment by varl** [comment]
>However, what is MOST IMPORTANT TO ME is that we are able to freely mix form-components from the@dhis2/final-form-fields with form-components that are created specifically for the app. So effectively, to me, that would mean:

Would it be possible to create a generic form component which could wrap an App-component so it would be compatible with `ui-forms`?

**Comment by amcgee** [comment]
> Would it be possible to create a generic form component which could wrap an App-component so it would be compatible with ui-forms?

Yes, it should be.  Ideally we'd own the API there as well, but it could be RFF-compatible.  From above:

```
import { CustomField } from '@dhis2/ui-forms'

<CustomField name="custom">
  ({ input, meta }) => (
    <MyCustomFieldComponent {...myFancyLocalProps} {...input} myCustomError={meta.error} />
  )
</CustomField>
```

**Comment by HendrikThePendric** [comment]
@amcgee 
> I don't think what we're each talking about here is all that different under the hood

You're probably right. And similar to offering a low-level async component that complements the `DataRequest` component, a low-level `CustomField` component would enable the developer to have sufficient flexibility. I believe this level of flexibility is important for two reasons:
1. Adoption rate of the form lib in the short term
2. It will prevent too many form-field components from popping-up that actually only have a single use-case

In retrospect, the discussion I started about the form-lib was almost identical to the discussion we had about the data-components, and in both cases you have addressed my concerns. Thanks for taking the time to explain.

@varl 
> Would it be possible to create a generic form component which could wrap an App-component so it would be compatible with ui-forms
Yes, pretty sure this is the `<CustomField>` Austin is referring to

**Comment by Mohammer5** [comment]
Let's summarize what we need the `ui-forms` lib to be capable of:

1. Provide form components (form, text, password, email, select, checkbox, radio buttons)
1. Provide an abstract field component so apps can have single use input fields
1. Provide DHIS2 form components (OrgUnitTree, PeriodPicker) - We could add these later with iterative steps

Should this app also expose some kind of form wizard api?
(With react-final-form I don't really see a way around it as every single page needs to be a `<form />` itself, afaik (that's my current knowledge from what I've seen so far)
