### ISSUE TITLE
[meta] - co-locate decisions in one file or folder, rename decisions => minutes

### ISSUE THREAD

**Issue by amcgee** [dhis2/notes#253]
In our `notes` repository we have a `decisions` directory with a date-organized sub-tree.  The content is actually mostly meeting notes, with a few concrete decisions sprinkled throughout.  It is practically very difficult to find the decisions, policies, etc. if you don't remember in which meeting the decision was actually made (so practically impossible for new folks).  Also in the cases where decisions are revised or changed over time, the 'immutable' previous meeting notes still exist and could be mistaken for the canonical source.

There's a lot we could do to improve the centralization of policies and workflows, but as a simple improvement I'd like to propose two simple changes:

1. Rename `decisions` to `minutes` or `meetings` or `meeting-notes` or similar to reflect the content
2. Extract the actual, concrete decisions into a single document `decisions.md` (or maybe a flat directory called `decisions` with a `README.md` index) and link it from the root `README.md`.  When meeting notes are added, any decisions made should update that canonical location, which can later be easily referenced when concrete actions need to be taken.

**Comment by varl** [comment]
Agreed.

The intention was that all meeting minutes should contain decisions; why else have a meeting ?

In practice that has been hard to enforce as discussion meetings are commonly used to "speed things up". Generally I disapprove of that tactic because it breaks asynchronous work and organisation, forcing everyone to drop what they are doing and get involved in something they may not be prepared enough to discuss or decide on.

Let's adapt the repo to the reality and not the other way around !

**Comment by Mohammer5** [comment]
:tada: I like the idea.
I'm wondering though if we should link to the meeting minutes with the decision instead of putting it into the decisions readme itself. That way all we'd have to do is to update the link to the current decision or add multiple links if a meeting just tackles a certain aspect of a decision. If we notice that links are not enough, with this we still have the option to add custom content / summaries to the decisions readme

**Comment by amcgee** [comment]
I think we should definitely link to the relevant minutes!  I would prefer to keep the "summary" of whatever the decision is in the decisions doc though, so that there is one canonical and concise place to find them rather than needing to click through links and read through minutes (which might included multiple decisions and unrelated discussion)

**Comment by amcgee** [comment]
Closed in #267
