### ISSUE TITLE
Validation of config objects

### ISSUE THREAD

**Issue by erikarenhill** [dhis2/notes#31]
So, discussing a PR with @Mohammer5 about a function with many parameters we decided to go with a config object instead.

E.g.
```
/**
* @param {number} a - the first number
* @param {number} b - etc....
*/
const fn = (a, b, c, d, e, f, g) => {
}
```
goes into
```
/**
* @param {object} config I have all the data!
* @param {number} config.a The first number....
* @param {number} config.b etc....
*/
const fn = ( config ) => { 
    const { a, b, c, d, e, f, g } = config
}
```

Then the discussion took fire and our thoughts went apart so we decided that a notes would be good to ventilate it with the team.

The 2 different takes at this is the following:

1. Strict validation of config objects either manually or with a Joi schema - **not allowing unknowns**
```
const def = joi.object().keys({
    a: joi.number().required(),
    b: joi.number().required()
})
```
This would make it **fail** if trying to pass `{ a: 1, b: 2, c: 3 }` because **c is not allowed**.

Instead if we'd like to allow c but have it optional we have to specify it as such.
```
const def = joi.object().keys({
    a: joi.number().required(),
    b: joi.number().required(),
    c: joi.number().optional
})
```

2. Loose validation, validating the specified schema, but **allowing unknown properties** 

This is easy to implement with Joi by just adding `stripUnknown: true` to the schema. The question is rather which of them we want to use. The 2'nd option would make the example pass for property `c` as unknown even if not specified as optional.

Personally I'd like to know if I pass an object with incorrect parameters even if they are unknown. For me, passing data to a function actually means that I expect them to be used (except optionals), not that it should be up to the function to swallow huge objects and use whatever they want to. So I'm for number 1

@Mohammer5 is on the other side and would like the second one.

Maybe we can set a standard for this in terms of both if we should use config objects where the amount of parameters exceed a specific count, and how they should be validated. Should we even use Joi (except in the app store backend where its a part for testing hapijs)? - or something else.

**Comment by Mohammer5** [comment]
Ok, so here's my POV:

First of all, I'd urge everyone to watch [Effective Programs - 10 Years of Clojure](https://youtu.be/2V1FtfBDsLU?t=2266) by Rich Hickey, I'm referring to the two slides "Information" and "The Information Programming Problem".

### 1. In general, we want to abstract our code.
If we specify the schemes that we expect to be matched 100% (no irrelevant information allowed), we're creating concretions, not abstractions. When looking at functions in isolation, there's no problem with that, but when looking at the bigger picture, there's no way to compose information easily as we'd have to extract/put together information all the time just to provide information in an exact schema.

### 2. Why should the function care
Passing arguments as an object is not the same as passing an object as an argument. When we use an object to specify the expected incoming parameters,

1. while we might iterate over an object that's passed as one specific argument, we'll never iterate over the arguments object (at least we shouldn't and I have never seen that anywhere so far), so the function still only uses what it needs, there's no "danger" by having "too much" in the payload.
2. the function's code won't change, except for the validation part (using the `stripUnknown` flag), if there's validation at all.

### My conclusion

1. When not caring about additional fields, we can compose information and pass it around without specifying types (a schema is more or less a class but even more specific/concrete).
2. Refactoring always takes more time the more types we have to deal with, which is why in FP we strive towards a minimum of types ("It is better to have 100 functions operate on one data structure than 10 functions on 10 data structures." Alan Perlis)

**Comment by ismay** [comment]
From a user's (developer using the lib) perspective, I find it convenient when a function that expects a lot of arguments uses an object, as the order of the arguments no longer matters and the names make it clear which is which. Requires less back and forth, less room for mistakes.

As for the validation, I think I'm with @erikarenhill here:

> Personally I'd like to know if I pass an object with incorrect parameters even if they are unknown. For me, passing data to a function actually means that I expect them to be used (except optionals), not that it should be up to the function to swallow huge objects and use whatever they want to. So I'm for number 1

As a user I want to know when something's wrong as early as possible. I understand @Mohammer5's argument. But I'm willing to accept the inconvenience of having to construct an object, if it means that the functions will tell me when I'm doing something wrong. Not that I'm expecting all our functions to have validations, but if I'd have to choose I'd go with that.

Plus constructing the object with parameters is often something you can do in-place (as in, with an object literal in the function parentheses), so to me it's fine. I prefer explicit over less work.

**Comment by Mohammer5** [comment]
> But I'm willing to accept the inconvenience of having to construct an object, if it means that the functions will tell me when I'm doing something wrong.

I was working with redux-observable on the weekend on one of my own projects.
An epic has the following structure:
```(action$, store$, dependencies) => action$```

dependencies can contain anything and will be only constructed once, during app setup, but different functions can extract different parts of the dependencies,
like `{ config }` or `{ dbConnection, config }`.

Same goes for functions that needs parts of a general app_config.js, you'd need to create a new object everytime a function wants to extract some values of the config object.

> As a user I want to know when something's wrong as early as possible.

Why is it wrong if a function gets more than it needs. It's only wrong once we declare it wrong.
The function won't ever fail if they get more than they needs.
If the function expects an argument to have a certain structure, of course then it should check for it, but that should only be the case when iterating over a collection.

But in the end, it's not too important to go this way, I just find it more convenient to be able to compose information

**Comment by ismay** [comment]
Maybe the two points don't have to exclude eachother. @Mohammer5 Your point demonstrates a case where it's convenient to have a parameter that contains a lot of different info (not all used by a single function). And easy composing seems nice as well of course.

In that case you could skip the strict checking.

In other cases, where it would help those consuming the function (if it's part of a lib or something), it'd be nice to notify the end-user asap when something's wrong. Maybe both approaches can live together.

**Comment by erikarenhill** [comment]
> It is better to have 100 functions operate on one data structure than 10 functions on 10 data structures.

I like that quote. It should use less memory passing the same object around by reference than creating new ones (but it would still be a shallow copy so still very small footprint in creating those). 

But lets compare this to how we use Redux, there are lots of functions operating on the same structure, but we still pick out the slices that we want to use in mapStateToProps.

If a component try to use something that we didn't slice out from the redux store, it wont work. But at the same time, passing more than the component use does not break it.

Thinking of it this way, I move towards that it would make sense allowing a larger object to be passed, if we at least validate the required properties (as we do with propTypes).

It would however also depend a bit on if we are thinking of introducing typescript or not, because then it would not allow passing in unknown properties in a defined type.

**Comment by ismay** [comment]
> It would however also depend a bit on if we are thinking of introducing typescript or not

Oh please no

**Comment by amcgee** [comment]
@ismay I like typescript, sounds like you don't?  I used it recently [here](https://github.com/amcgee/dhis2-app-service-data) as an experiment and proof of concept.  Once the build tooling is set up it's:
1) transparent to the library consumer (the output is just .js files)
2) replaces runtime prop-types checks with static compile-time checking
3) is well-supported for code completion and ms intellisense out of the box (even if the consumer is a pure js application)
4) compilation is really fast with `@babel/preset-typescript` which just strips the types and leaves checking to `tsc` or the editor.

>It would however also depend a bit on if we are thinking of introducing typescript or not, because then it would not allow passing in unknown properties in a defined type.

@erikarenhill what do you mean by this?  Typescript interfaces are [a thing](https://github.com/amcgee/dhis2-app-service-data/blob/master/src/DataProvider.tsx).

I don't find the TS syntax too unweildy, I think it's even more succinct and parsable than most of the alternatives in this thread, but that may just be me (I come from a C/C++ background).  Like any of these options it can be incrementally adopted, but I think there's a strong case for using a statically-typed superscript particularly when building api-focused composable libraries.

---

👍 I'm in favor of config objects over positional arguments, particularly because it allows for easier backwards-compatible api upgrades when those are required.

👍 I'm also in favor of interfaces (slicing input to allow extraneous properties) rather than formal types.  The simplest manifestation of this is object destructuring `{ a, b } = { a: 1, b: 2, c: 3, ... }` which works very well with config object function arguments.

**Comment by ismay** [comment]
> I like typescript, sounds like you don't? :-P

Sorry, didn't want to sound angry or anything, but  no I am not a big fan no 😊. I think this article by Eric Elliot sums up well why I personally don't think typescript adds much benefit vs the cost of using it: https://medium.com/javascript-scene/the-typescript-tax-132ff4cb175b

**Comment by erikarenhill** [comment]
> > It would however also depend a bit on if we are thinking of introducing typescript or not, because then it would not allow passing in unknown properties in a defined type.
> 
> @erikarenhill what do you mean by this? Typescript interfaces are [a thing](https://github.com/amcgee/dhis2-app-service-data/blob/master/src/DataProvider.tsx).

What I mean by this was more of a quick thought regarding the quick feedback in the IDE while working by which arguments and types a function requires (without adding the jsdoc just for that, but jsdocs should be added for docs anyway so..) and if there is a decision coming in the form of "lets move every dhis2 app to typescript".

Adding TS don't remove the need for input validation, and I'm generally pro for typescript. It has saved me in several other projects to not introduce bugs when refactoring, or to avoid making simple typos.

It's also really easy to add to an existing create-react-app project from version 2.1+: https://facebook.github.io/create-react-app/docs/adding-typescript

**Comment by erikarenhill** [comment]
Lets move the typescript discussion to another note if we want to continue discussing that.

**Comment by amcgee** [comment]
> Lets move the typescript discussion to another note if we want to continue discussing that.

Sounds good.

Proposed decisions for this thread:

1. Use objects with named parameters as function inputs, rather than positional arguments
2. Be liberal in what we accept as input objects, allowing extraneous parameters.

Does that sound right?  @ismay I think you may still have different opinions on 2?

**Comment by erikarenhill** [comment]
I started this thread by not agreeing with being liberal about input objects, but I also understand your arguments, so I guess it boils down to personal preference.

I'd like to add:
 

3.  **validate** the input object and not just let it pass through to let the code that expect it to crash

Quite often I see code just using the function parameters without checking if it's valid or even defined or not null before using them.

**Comment by ismay** [comment]
> Does that sound right? @ismay I think you may still have different opinions on 2?

I don't feel strongly about what direction we take on 2. I think my preference is more in line with @erikarenhill's comment:

> validate the input object and not just let it pass through to let the code that expects it, to crash

I prefer that as well. Not necessarily everywhere, but in general it's nice to have I think.
