### ISSUE TITLE
Application platform & appShell

### ISSUE THREAD

**Issue by amcgee** [dhis2/notes#36]
I will add a writeup about appShell and platform here when I have some time, but for now anyone who attended the appShell intro today feel free to share thoughts, questions, and concerns here!

**Comment by HendrikThePendric** [comment]
First off, I really liked the ideas of an app shell and think it can speed the early stages of app development significantly, and could provide additional benefits too. If the app-shell evolves until, in the end, the entire DHIS2 platform is one giant SPA, then we must make sure that it is impossible for errors within an app to ever bubble up to the app-shell and block that. It should always be possible to navigate to another app and get a "fresh-start".

I also like the idea of the `DataProvider` and `DataRequest` components, but think we need to be careful to start with a very low-level implementation, and add convenience methods/props over the top of that. From the presentation, I have understood that the `DataRequest` component is going to delegate most of its work to the `DataProvider` component. I think we should build both components so that that the `DataProvider` **can** do most of the heavy lifting, but it can also take more specific instructions from a `DataRequest`. I'll try to explain....

Suppose, you have `DataRequest` component with only one prop `resourcePath`, as it is in the [current POC version of the component](https://github.com/amcgee/dhis2-app-service-data/blob/master/src/DataRequest.tsx):
```javascript
<DataRequest resourcePath={`/users/${userId}.json` />
```
Obviously this naive implementation has a lot of limitations. Some I can think of from the top of my head:
- Can only do GET
- Assumes we want to query the DHIS2 api
- No room for transforming/filtering/reducing the response object
- No possibility for doing multiple parallel requests
- Etc. etc.

Instead of providing more props, and handling more and more cases, and exceptions, I think we should expose a few low-level properties on the `DataRequest` component that can be used by the `DataProvider` component to do its thing. For example, something like this:
- `request`: a async function
- `requestArgs`: an array of arguments (perhaps allow an object too)
And then if the `request` property is present on the `DataRequest`, the `DataProvider` will do something like this:
```javascript
// ...
fetch: (resourcePath, options, request, requestArgs) =>
    request
        ? request.apply(null, requestArgs || []) 
        : fetchData(joinPath(apiUrl, resourcePath), options),
    
// ...
``` 
Also, in general, we need to consider how this approach fits in with things like REDUX and FinalForm....

**Comment by amcgee** [comment]
Thanks for the comments @HendrikThePendric!

Before diving into the specific points you made about `<DataRequest>`, a quick question:

**What use case do you see for requesting non-DHIS2 API data?**  I see this as specifically tailored for that information, and I don't see us able to make many external requests from our applications (at least initially) because of the possibility of proxies, firewalls, and high-latency pipes.  This is why we don't use external CDNs to load javascript libraries, for instance.  There might be a use case I'm missing here, but if so I think it would be outside the scope of this data service.

Regarding your points -
1. *Can only do GET* - yes, as is in the POC that's true but it would be fairly trivial to add support for writes as well as reads.
2. *Assumes we want to query the DHIS2 api* - See above
3. *No room for transforming/filtering/reducing the response object* - There is room for this, actually, in two places - you can tranform/filter/reduce the `data` prop provided to the `({ loading, error, data }) => {}` to your heart's content, though that will happen on every load unless you're careful about memoizing the transformation.  The second, and more powerful, place to do this would be in the data engine itself - so effectively you could request "users with admin permissions in org unit 7" and the engine would return exactly what you request, even though behind the scenes this might do 3 different queries to the backend to fetch users, assignedPermissions, and orgUnits (for instance).  Those results would then be filtered and reduced to yield the expected result.  This is a bit more advanced, obviously, than the trivial version in the POC.  Effectively this is aligning with the paradigm of supporting a **client-driven API** for data access.  Initially, this could be done in the shell layer to translate some combination of network requests and cache lookups into the format expected by the data consumer (whoever used `<DataRequest />`).  This brings us to the GQL point below.
4. *No possibility for doing multiple parallel requests* - We definitely need this, but ideally the `<DataRequest>` consumer shouldn't need to have any concept of a request at all - it should just care about data (probably something like `<DataQuery>` would be a better name, once we get there).  Naively asynchronous requests could be supported by allowing curried `<DataRequest />` components, something like:

```
<DataRequest resourcePath='indicators.json' key='indicators'>
    <DataRequest resourcePath='users.json' key='users'>
        {({ loading, error, data }) => {
            // data.indicators and data.users are populated
        }
    </DataRequest>
</DataRequest>
```

It could more succinctly be achieved by supporting multiple resource requirements within a single logical DataRequest, i.e.

```
<DataRequest resourcePaths={{
   indicators: 'indicators.json',
   users: 'users.json'
}}>...</DataRequest>
```

The latter is obviously a bit cleaner, but as you alluded to it gets a bit messy when you have a bunch of parameters for each request (assuming we've moved past just pasting everything into query strings, which we want to do):

```
<DataRequest query={{
   indicators: {
      resource: 'indicators',
      where: 'orgUnit=42',
      limit: 10,
      offset: 20
   },
   users: {
      resource: 'users',
      where: 'orgUnit=42&role=admin',
      limit: 1,
   }
}}>...</DataRequest>
```

### GQL

At this point, we've basically invented a client-defined relational query engine.  It turns out this already exists in [GraphQL](https://graphql.org/learn/) and [Apollo Client](https://www.apollographql.com/docs/react/essentials/queries) (some of those concepts may look familiar ;-) ).  I definitely foresee us moving towards supporting rich, relational queries through this data access layer and I'd love to see us support GraphQL on the backend **in front of the existing API** so that we can streamline the network layer for application data requests.  Until we get there (or decide to go somewhere else) though, a naive delegated data fetching mechanism allows us to consolidate and standardize a lot of our logic in one place without changing the DHIS2 network stack.

---

Finally to your suggestions about adding low-level `request` function primitives to the `<DataRequest>` API - I actually think this defeats the purpose of the data engine.  If we allow the fetching logic to be overridden, then it will be overridden and we're not able to improve or change the data fetching layer (for instance to maintain and use a normalized cache).  What may be confusing is that in the POC we're just passing through a URL path to an API resource.  **This is NOT what we want to do long-term** - it gives us incremental benefits by centralizing the request processing logic, but it tightly couples presentational components with the API URL, schema, etc.  The goal is to support **declarative data dependencies** - so a component declares the data it needs (and doesn't care where the data comes from or how it's fetched), rather than imperatively fetching that data itself.  I think allowing low-level overrides of the fetching logic impedes this goal.

That being said, there could be room for a lower-level primitive for separating arbitrary asynchronous processes from a presentational component.  Often Redux (thunk|epic|observable) is used to do this, but most of the time that is overkill.  If the desire is to make non-DHIS2 data requests (see question above) or perform other asynchronous tasks in React presentation layer, maybe a simple low-level async component could make sense.

---

Apologies for the long-winded explanation, hopefully it makes sense!  Do you anticipate use cases that won't fit into this model or will be hindered by moving to a naive `<DataRequest resourcePath={...} >` delegated fetching system as an intermediate step?

**Comment by HendrikThePendric** [comment]
Thanks @amcgee for the detailed response.

The limitations of the current POC implementation I mentioned were probably poorly chosen. I was just trying to illustrate how over time more and more use-cases emerge and trying to cater for all of these use-cases by adding more props and conditions in the components would not make for a maintainable solution in the long run. I think I didn't get that point across very clearly, apologies for that.

But despite of the misunderstanding, you have fully addressed my main concern:
> That being said, there could be room for a lower-level primitive for separating arbitrary asynchronous processes from a presentational component. Often Redux (thunk|epic|observable) is used to do this, but most of the time that is overkill. If the desire is to make non-DHIS2 data requests (see question above) or perform other asynchronous tasks in React presentation layer, maybe a simple low-level async component could make sense.

I think it's important that we do provide something like this. I am a stickler for consistency. If we were to introduce the concept of data-components into our code bases, I would like to use that pattern throughout. By offering some low-level async component, this would be made possible. Keeping this low-level component completely separate from the DataRequest/DataProvider makes perfect sense.

I think the above is most important, but I will also respond to the other points in your comment.

---
> What use case do you see for requesting non-DHIS2 API data?

In theory there is no need for it, and I am not reaching out to another domain in any of the apps I've worked on so far. I do know of 1 or 2 apps that still reach out to an old `/action` endpoint, and these are not under `/api`, instead it's something like this:
`<INSTANCE_URL>/<APP_NAMESPACE>/action.<SOME_NAME>`
This type of thing is very irregular, and will be phased out. If there is a low level async component, then this case could be handled by that.

> The second, and more powerful, place to do this [transforming/filtering/reducing the response object] would be in the data engine itself 

I agree that it makes a lot of sense to do that here. Assuming this type of behavior is app-specific, that implies it is possible to configure the data-engine per app. Is this correct? If so, how would this work? And when you refer to the _data-engine_ is this equivalent to the `DataProvider` component, or another layer?

As you can probably tell by now, I have no experience with Apollo/GraphQL. Since a lot of the concepts we are talking about right now are borrowed from that ecosystem, it would be good if I studied the basics of that. If you know of an article/tutorial that gives a good top-level overview, that would be great.

---

Finally I was also wondering about events that could possibly trigger a request. Suppose I have some filtered-list component. I want to fetch the list when the component mounts, but I also want to do a new fetch when the user applies a filter. I think this type of thing is a pretty common pattern. How would that work?

---
I was already very excited about the appShell concept, and the more I am thinking/reading about these data-components, the more enthusiastic I am becoming about them too 👍

**Comment by janhenrikoverland** [comment]
Regarding @amcgee 's comment to point 3:

When I go to a restaurant I would like to choose from a menu I understand (client driven API) and order a complete meal (transformed/combined/sorted/prepared data). Unless I just want a single ingredient (resource) I don't want to request all the ingredients directly from the kitchen (web API) and compose the meal myself. And look at all the other customers doing the same. I want a chef (layer in between) who is an expert at it to do that for me and I don't really care how he does it as long as the result looks/tastes according to my expectation and it doesn't take too long. The next time a come by they somehow knew already and the meal was instantly ready.

**Comment by Mohammer5** [comment]
Right now I'm struggeling with telling the `useDataQuery` hook to request a given resource again, it only happens once. I'd have to unmount/mount the component that uses the `useDataQuery` hook in order to achieve that.

It would be nice if the package/lib provided a `fetch` function, that accepts the part of a query (that we would pass to the hook) of one particular resource. It should be fairly easy to refactor that and move it to the hook's query once the limitations of the hook/component are gone (like caching, forced reloading, POST/PUT/DELETE requests).

While the functionality is likely to be implemented in the future, right now I don't have any access to the `Context` of the data provider, so I can't use it as a single source of truth for the api meta data (base url, version, etc). I'd like to have access to [these values](https://github.com/dhis2/app-runtime/blob/master/services/data/src/context/defaultContext.ts).

**Comment by amcgee** [comment]
@Mohammer5 can you give an example of the use case where you want to re-fetch data?  I agree it should be supported, and wouldn't be too hard to do, but I want to make sure we do it the right way and I'm not sure a `fetch` function is correct - I might suggest moving towards data subscriptions rather than requests (initially just re-fetching on a schedule automatically and using the API to minimize duplicate data) to support data requests which change over time.

**Comment by Mohammer5** [comment]
@amcgee I like the idea of subscriptions a lot more, just didn't dare to ask for that.. hehe

The organisation unit tree has a force-reload capability. I think it's because children can be added and in order to update the view, the parent needs to reload it's children, but the request data doesn't change.

**Comment by HendrikThePendric** [comment]
> I think it's because children can be added and in order to update the view, the parent needs to reload it's children, but the request data doesn't change.

There is one place in the maintenance app where you can define the org unit hierarchy. Pretty sure this is where we would want to reload it. Just to provide some context....

**Comment by amcgee** [comment]
@Mohammer5 I see, that might be best-served with a `reload()` callback, since it's user-initiated (am I envisioning this correctly as like a "reload" button?).

You should be able to un-mount and re-mount the whole tree component to get the behavior you want with the current implementation right?  It might be a bit harder to call `reload()` in a bunch of nested components..

**Comment by Mohammer5** [comment]
@amcgee [Here](https://github.com/dhis2/ui-widgets/pull/10) you can see the current state of the org unit tree that I came up with.

> am I envisioning this correctly as like a "reload" button?

In the maintenance app, there's an org unit tree at the bottom of the sidebar. When adding a new unit, the tree needs to be updated. But loading the whole tree again would be very expensive in terms of network traffic.

> You should be able to un-mount and re-mount the whole tree component to get the behavior you want with the current implementation right?

With my current approach I only need to re-mount the path that needs to be updated (as each unit loads its own children), it's a recursive approach, similar to the old version.

The `src/OrganisationUnitTree/OrgUnitTree.js` component contains both a class (`_OrgUnitTree`) and a function (`OrgUnitTree`).
The class is the way to go if the component needs to do the request manually / itself.
If the `useDataQuery` worked with caching and forced reloading, then the SFC would be a much nicer / cleaner solution.

What I thought of right now is: There's a `forceReloaded` prop which accepts an array of paths to reload.
And an org unit's path is inside that array, it will have to trigger the reloading somehow.
The class does that very primitively, by checking whether the array has changed && the path is inside, with the `componentDidUpdate` methog.

**Comment by amcgee** [comment]
Thanks @Mohammer5 for the context, I'm almost done with adding support for `abort` so ll take a look at adding `reload` (and maybe subscriptions...) as well first thing next week

**Comment by varl** [comment]
This is superseded by #56, #63, and #64.

The `reload` use case is documented and covered in #63.
