### ISSUE TITLE
Next Tapps Meeting

### ISSUE THREAD

**Issue by Mohammer5** [dhis2/notes#77]
Hey folks (@dhis2/team-apps & @amcgee)

There are several things we need to discuss, so I think I'll just write down what I currently have in my head (@varl feel free to take over this issue and rename title and change the description in any way you see fit)

## 1. How to proceed with the new Maintenance app

I've gotten quite far and reached a state where I don't want to continue working alone on this.
There are too many opinions and people involved.
So I think we need to talk about the next steps and prioritization. @varl mentioned we'll get some time for the new app this autumn but I don't know if that's still valid, how much time we can spend on it and how we should prioritize it in regards to other issues on our board. ([Link to the repo](https://github.com/dhis2/mar-y) & [Link to the JIRA epic](https://jira.dhis2.org/browse/TECH-223)). There is one open issue which I think is worth reading through. 

## 2. Error reporting

This is a cross-team effort, but we need to get it started somehow. I've porposed we (the devs) come up with an initial proposal so we have something to talk about.
It'll be quite hard to get all devs involved in this at once, so I think we (and @amcgee, who created the first JIRA issue about this) should come together and talk (ideally prepared, I've written down my thoughts here: #76)

## 3. Positioning engine (internal vs external vs very simple solution)

@cooper-joe has created a PR with features. I tried to improve some things from a dev perspective:
* Joe's PR: dhis2/ui-core#522
* My improvements: dhis2/ui-core#527

We can talk about his proposals and how we should act based on them

## 4. Remotes & remote culture

Lately I feel quite disconnected from dhis2 and I guess I'm not the only one. We have more or less properly working communication between remotes (due to the nature of working remotely). But it feels more and more demotivating that dhis2 itself it not really trying to adopt a remote culture.

I think it's crucial for dhis2 to hire remotes as we're understaffed even with the remotes we currently have. Which is why I think we should put more pressure on making it more remote friendly.

* I have no idea what's happening in Oslo (discussion wise).
Us remotes use GitHub actively, especially discussing stuff in `dhis2/notes`, but the lack of participation of others is not good (also from a functional cross team workflow perspective)
* It normally requires some waiting time if remotes need information
Asking a question on the `#webapi` channel sometimes takes a few attempts before being answered, sometimes there's no response whatsoever. It feels like we have to be pro-active all the time

I know this is not intentional and I also don't really know what we can do to change it. But we should address it and talk about possible solutions (hiring more BE remotes? hiring a remote team coach? Enforcing certain good practices like meetings where everyone uses his/her own computer? Enforcing discussions taking place on GitHub (no idea if that's even possible)? Use some work time to organize some kind of social online event that's entirely unrelated to work?)
This should be addressed in a very constructive way without any shaming at all! I'm not trying to criticize anyone, just the historically-explainable structures in place.

## 5. Documentation of our libraries

I'll just quote @amcgee here:

> And want to reiterate the Tutorial / How-To Guides / Reference / Conceptual Explanation documentation quadfecta, we should have all 4

Assuming that all of us think that this is important, we need to craft a plan how to proceed.
I've already proposed the following:

> I think we should create an epic, then tasks, then assign them
> Maybe have a meeting beforehand to align what part should document what and in what way

**Comment by varl** [comment]
Thanks for the initiative, @Mohammer5. 👏 

Let's have a meeting ASAP, I've created an event for **Monday, 4 November 14-16 CET**.

**Comment by HendrikThePendric** [comment]
Since I need to be AFK for approx 30 minutes during this meeting, I will briefly summarise my thoughts where relevant below:
- **Mary**: N/A (I shared a lot of my opinions [here](https://github.com/dhis2/mar-y/issues/47))
- **Error reporting**: N/A (I only have some experience in error reporting for a traditional .NET MVC application, so haven't got much to bring to the table there)
- **Remotes**: I do recognise some of the points raised here. But I also think that it's not necessarily something that is happening all the time, there seem to be peek moments for on-site people that us remotes don't know about. In general, I think it would be great if people that tend to get a lot of questions, would dedicate some specific time-slots in their calendar to answering questions. This would probably make things more efficient overall, and a lot lees frustrating for remotes.
- **Docs**: on the one hand I recognise the need for more and better docs. On the other hand, I have noticed that keeping all these jsDoc comments up-to-date with the code-base is very error prone and cumbersome. I don't really know where to take this...
